# Numpy Overal Review

Loading Numpy 


In [1]:
import numpy as np


            The basics


In [2]:
a = np.array([1,2,3],dtype="int16") # if the data is small you can determine the data type to int16
print(a)

# a list within a list
b = np.array([[2.2,3.4,5.6],[3.4,4.0,5.8]])
print(b)

#Getting the dimensions of the array
b.ndim






[1 2 3]
[[2.2 3.4 5.6]
 [3.4 4.  5.8]]


2

In [3]:
# getting the shape of the array
b.shape

#getting the  type of the array
a.dtype


dtype('int16')

In [4]:
#getting the size
a.itemsize
b.itemsize


8

In [5]:
#geting the total size
a.size

a.nbytes


6

        Accesssing/Changing specific elements , rows ,columnns etc

In [6]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
#getting a specific element [r,c]

c[1,-1] #indexing  starts at zero  

14

In [8]:
#get a specific row
c[0,:]  

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#Getting a specifc column

c[:,2]

array([ 3, 10])

In [10]:
#Getting the more specific ranges of elements in the data use [startindex:endindex:stepsize]
c[0,1:-1:2]

array([2, 4, 6])

In [11]:
#Changing the elements
c[1,5] = 33

c[:,2] =[100,100]
print(c)

[[  1   2 100   4   5   6   7]
 [  8   9 100  11  12  33  14]]


In [12]:
# **3D example
d =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#getting a specific element
d[:,1,:] = [[100,100],[1000,1000]]
print(d)


[[[   1    2]
  [ 100  100]]

 [[   5    6]
  [1000 1000]]]


        Initializing Different types of Arrays


In [14]:
 # all zeros matrix
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#All 1s matrix
np.ones((4,2,2),dtype ="int32") # its not a must to specify the data type unless required

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
#Any other number
np.full((2,2),100) # takes in the shape of the matrix and the number to be filled in the matrix


array([[100, 100],
       [100, 100]])

In [21]:
#Any other number (full_like)
np.full_like(c,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
#alternatively this can be done as
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
#Random Deciamal numbers
np.random.rand(4,2,3)

array([[[0.72408307, 0.88017776, 0.10647896],
        [0.88322581, 0.30448241, 0.72143428]],

       [[0.35961092, 0.367956  , 0.44421046],
        [0.3209153 , 0.98150628, 0.36092568]],

       [[0.23925265, 0.64033595, 0.594616  ],
        [0.71856688, 0.50255918, 0.79097485]],

       [[0.13850137, 0.73751527, 0.81000165],
        [0.79094721, 0.63376153, 0.80910765]]])

In [30]:
#Random integer values

np.random.randint(7,size=(3,3)) # random integers from 0 to 6 since it is exclusive

array([[6, 0, 4],
       [0, 5, 1],
       [0, 2, 2]])

In [36]:
#Random integers using ranges e.g 4 to 7 and 7 being included
np.random.randint(4,8,size=(3,3))

array([[5, 6, 5],
       [7, 7, 6],
       [6, 7, 7]])

In [40]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#Repeat an array

arr1 =np.array([[1,2,3]])
r1 = np.repeat(arr1,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
#examples
output = np.ones((5,5))


z = np.zeros((3,3))

z[1,1] =9
print(z)
output[1:-1,1:-1] = z
print(output)


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


         Be careful when copying arrays!!!

In [57]:
aa = np.array([1,2,3])
bb = aa.copy()
bb[0] = 100
print(aa)
print(bb)


[1 2 3]
[100   2   3]


            Mathematics 

In [63]:
arr = np.array([1,2,3,4])
print(arr)

arr +2
arr * 2
arr **2  #basic arrithmetic can be done in numpy same as in python


[1 2 3 4]


array([ 1,  4,  9, 16])

In [67]:
print (arr)

# take the sin
np.sin(arr)
np.cos(arr)

[1 2 3 4]


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra


In [72]:
a = np.ones((2,3))


b = np.full((3,2),2)

#  multiply  matrices use np.matmul()
np.matmul(a, b)


array([[6., 6.],
       [6., 6.]])

In [73]:
#finding the determinant  
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#for all linear algebra things such as Determinant, Eigenvalues, etc...


        Statistics

In [79]:
stats =np.array([[1,2,3],[4,5,6]])
stats 

np.min(stats)




1

In [81]:
np.max(stats)
#you can specify the rows so as to get the desired statistic using the axis instance

np.max(stats,axis = 1)


array([3, 6])

In [86]:
np.sum(stats ,axis = 1)


3.5

        Reorganising Arrays

In [92]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [96]:
#vertically stacking vectors/Matrices

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2,v1,v2])




array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
#horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h2,h1))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

## General knowledge

        Load Data from a File 

In [106]:
#loading a txt file
file = np.genfromtxt('modified.txt',delimiter="\t")
file

array([[  1.,  nan,  nan, ...,  65.,  45.,   1.],
       [  2.,  nan,  nan, ...,  80.,  60.,   1.],
       [  3.,  nan,  nan, ..., 100.,  80.,   1.],
       ...,
       [720.,  nan,  nan, ..., 130.,  70.,   6.],
       [720.,  nan,  nan, ..., 130.,  80.,   6.],
       [721.,  nan,  nan, ...,  90.,  70.,   6.]])

##### Boolean masking and Advanced Indexing

In [107]:
file >50

array([[False, False, False, ...,  True, False, False],
       [False, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False],
       ...,
       [ True, False, False, ...,  True,  True, False],
       [ True, False, False, ...,  True,  True, False],
       [ True, False, False, ...,  True,  True, False]])

In [108]:
#indexing where the certain conditions are satisfied
file[file >50]

array([318.,  65.,  65., ..., 130.,  90.,  70.])

In [110]:
#indexing using a list in Numpy
a =np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]


array([2, 3, 9])

In [115]:
#checking if any values fit a certain threshold
np.any(file , axis = 0) #this is done vertically


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [116]:
#to check if all values fit a certain threshold
np.all(file , axis = 0) # when axis is 1 it checks the rows


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [119]:
#similar to pandas to pass in multiple conditions
((file > 50) & (file < 100))

array([[False, False, False, ...,  True, False, False],
       [False, False, False, ...,  True,  True, False],
       [False, False, False, ..., False,  True, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True,  True, False]])

In [121]:
#this is to reverse select (to not meeet the conditions i.e ~ is used to  represent not)
(~((file > 50) & (file < 100)))

array([[ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ..., False, False,  True],
       [ True,  True,  True, ...,  True, False,  True],
       ...,
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True,  True, ..., False, False,  True]])

In [137]:
file[2:4 , 0:2] #extreacting the 2nd and 3rd row and the 0th and 1st column


array([[ nan,  nan, 318.,  45.,  49.,  49.,  65.,  65.,  45.,   1.],
       [ nan,  nan, 309.,  39.,  52.,  43.,  60.,  50.,  65.,   1.],
       [ nan,  nan, 405.,  58.,  64.,  58.,  80.,  65.,  80.,   1.]])

In [138]:
file[[0,1,2,3],[1,2,3,4]]



array([nan, nan, nan, nan])

In [139]:

file[[0,4,5],3:]
        

array([[ nan,  nan, 318.,  45.,  49.,  49.,  65.,  65.,  45.,   1.],
       [ nan,  nan, 309.,  39.,  52.,  43.,  60.,  50.,  65.,   1.],
       [ nan,  nan, 405.,  58.,  64.,  58.,  80.,  65.,  80.,   1.]])