# Numpy Overal Review

Loading Numpy 


In [1]:
import numpy as np


            The basics


In [2]:
a = np.array([1,2,3],dtype="int16") # if the data is small you can determine the data type to int16
print(a)

# a list within a list
b = np.array([[2.2,3.4,5.6],[3.4,4.0,5.8]])
print(b)

#Getting the dimensions of the array
b.ndim






[1 2 3]
[[2.2 3.4 5.6]
 [3.4 4.  5.8]]


2

In [3]:
# getting the shape of the array
b.shape

#getting the  type of the array
a.dtype


dtype('int16')

In [4]:
#getting the size
a.itemsize
b.itemsize


8

In [5]:
#geting the total size
a.size

a.nbytes


6

        Accesssing/Changing specific elements , rows ,columnns etc

In [6]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
#getting a specific element [r,c]

c[1,-1] #indexing  starts at zero  

14

In [8]:
#get a specific row
c[0,:]  

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#Getting a specifc column

c[:,2]

array([ 3, 10])

In [10]:
#Getting the more specific ranges of elements in the data use [startindex:endindex:stepsize]
c[0,1:-1:2]

array([2, 4, 6])

In [11]:
#Changing the elements
c[1,5] = 33

c[:,2] =[100,100]
print(c)

[[  1   2 100   4   5   6   7]
 [  8   9 100  11  12  33  14]]


In [12]:
# **3D example
d =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#getting a specific element
d[:,1,:] = [[100,100],[1000,1000]]
print(d)


[[[   1    2]
  [ 100  100]]

 [[   5    6]
  [1000 1000]]]


        Initializing Different types of Arrays


In [14]:
 # all zeros matrix
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#All 1s matrix
np.ones((4,2,2),dtype ="int32") # its not a must to specify the data type unless required

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
#Any other number
np.full((2,2),100) # takes in the shape of the matrix and the number to be filled in the matrix


array([[100, 100],
       [100, 100]])

In [21]:
#Any other number (full_like)
np.full_like(c,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
#alternatively this can be done as
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
#Random Deciamal numbers
np.random.rand(4,2,3)

array([[[0.72408307, 0.88017776, 0.10647896],
        [0.88322581, 0.30448241, 0.72143428]],

       [[0.35961092, 0.367956  , 0.44421046],
        [0.3209153 , 0.98150628, 0.36092568]],

       [[0.23925265, 0.64033595, 0.594616  ],
        [0.71856688, 0.50255918, 0.79097485]],

       [[0.13850137, 0.73751527, 0.81000165],
        [0.79094721, 0.63376153, 0.80910765]]])

In [30]:
#Random integer values

np.random.randint(7,size=(3,3)) # random integers from 0 to 6 since it is exclusive

array([[6, 0, 4],
       [0, 5, 1],
       [0, 2, 2]])

In [36]:
#Random integers using ranges e.g 4 to 7 and 7 being included
np.random.randint(4,8,size=(3,3))

array([[5, 6, 5],
       [7, 7, 6],
       [6, 7, 7]])

In [40]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#Repeat an array

arr =np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
#examples
output = np.ones((5,5))


z = np.zeros((3,3))

z[1,1] =9
print(z)
output[1:-1,1:-1] = z
print(output)


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
